### PR TITLE
Delete useless files and relocate files

### PR DESCRIPTION
**Pull request by LeeTaeSoon**
Delete previous example files and relocate files

### CODE REVIEW

**Comment by JeffGuKang** [comment]
Good. 
I think it will be better if the `index.ejs` file move to `views` folder. 
As structure of https://scotch.io/tutorials/use-ejs-to-template-your-node-application.

**Comment by LeeTaeSoon** [comment]
good idea.  I applied your comment

**Review by JeffGuKang — APPROVED** [review]

**Comment by LeeTaeSoon** [comment]
It is recommend `npm install` before `npm run`

**Comment by JeffGuKang** [comment]
`views/pages` is wired name. Use just `views`.

**Comment by LeeTaeSoon** [comment]
I changed the folder

**Comment by TylerShin** [comment]
🐸

**Pull request merged**
